const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Json,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Json.Acts.RemoveValues,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.ScriptsInEvents.Es_common_Event20_Act7,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.ScriptsInEvents.Es_common_Event23_Act8,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.ScriptsInEvents.Es_common_Event30_Act1,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{Touch: 0},
	{Browser: 0},
	{JSON: 0},
	{Audio: 0},
	{Index: 0},
	{Enabled: 0},
	{isCorrect: 0},
	{value: 0},
	{Selected: 0},
	{btnOption: 0},
	{Tween: 0},
	{bgQuestion: 0},
	{txtQuestion: 0},
	{btnSubmit: 0},
	{txtBtnLabel: 0},
	{index: 0},
	{txtOptions: 0},
	{DiceAnimationgif: 0},
	{txtClickANy: 0},
	{Anchor: 0},
	{TiledBackground: 0},
	{GameTitle: 0},
	{bgLudo: 0},
	{shadow: 0},
	{Particles: 0},
	{Rotate: 0},
	{Sine: 0},
	{Confetti2: 0},
	{Id: 0},
	{settingBtn: 0},
	{soundOffBtn: 0},
	{musicBtnIcon: 0},
	{settingsBtnIcon: 0},
	{homeIcon: 0},
	{StartX: 0},
	{sfxBtn: 0},
	{musicBtn: 0},
	{homeBtn: 0},
	{BlackOverlay: 0},
	{bgInstruction: 0},
	{txtInfoHeading: 0},
	{btnInfoClose: 0},
	{closeIcon: 0},
	{closeIcon2: 0},
	{Buttons: 0},
	{correctAnswer: 0},
	{currentQuestion: 0},
	{score: 0},
	{isQuestionsLoaded: 0},
	{attemptedQuestionsIndeces: 0},
	{won: 0},
	{tt: 0},
	{tween_time: 0},
	{uid: 0},
	{sfxVolume: 0},
	{musicVolume: 0},
	{isMusic: 0},
	{isSFX: 0},
	{rand_anim_frame: 0},
	{show: 0},
	{name: 0},
	{tag: 0},
	{vol: 0},
	{loop: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Audio: class extends self.IInstance {},
	btnOption: class extends self.ISpriteInstance {},
	bgQuestion: class extends self.ISpriteInstance {},
	txtQuestion: class extends self.ITextInstance {},
	btnSubmit: class extends self.ISpriteInstance {},
	txtBtnLabel: class extends self.ITextInstance {},
	txtOptions: class extends self.ITextInstance {},
	DiceAnimationgif: class extends self.ISpriteInstance {},
	txtClickANy: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	GameTitle: class extends self.ISpriteInstance {},
	bgLudo: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Confetti2: class extends self.ISpriteInstance {},
	settingBtn: class extends self.ISpriteInstance {},
	soundOffBtn: class extends self.ISpriteInstance {},
	musicBtnIcon: class extends self.ISpriteInstance {},
	settingsBtnIcon: class extends self.ISpriteInstance {},
	homeIcon: class extends self.ISpriteInstance {},
	sfxBtn: class extends self.ISpriteInstance {},
	musicBtn: class extends self.ISpriteInstance {},
	homeBtn: class extends self.ISpriteInstance {},
	BlackOverlay: class extends self.ISpriteInstance {},
	bgInstruction: class extends self.ISpriteInstance {},
	txtInfoHeading: class extends self.ITextInstance {},
	btnInfoClose: class extends self.ISpriteInstance {},
	closeIcon: class extends self.ISpriteInstance {},
	closeIcon2: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}